#!/usr/bin/env python

import argparse
from zipfile import ZipFile
from os import path
import yaml

DEFAULT_CONFIG_PATH = "~/.config/confgit.yml"
CONFIG = None


def init():

def sync():
    # git pill
    # nakopírovat configy na originy
    pass


def update():
    # nakopírovat configy na jejich
    pass


def backup():
    file_paths = []
    for root, directories, files in os.walk(CONFIG.config_repo_filder):
        for filename in files:
            filepath = path.join(root, filename)
            file_paths.append(filepath)


def get_arguments():
    parser = argparse.ArgumentParser(
        description="Git overhead for version control of your config files",
        formatter_class=argparse.RawTextHelpFormatter,)
    parser.add_argument("actions", nargs="+", help="help page")
    parser.add_argument("sync", action="")
    parser.add_argument("update")
    parser.add_argument("backup")
    return parser.parse_args()


def load_config(config_file_path):
    if config_file_path is None:
        config_file_path = DEFAULT_CONFIG_PATH
    config_file_path = config_file_path.replace("~", str(path.expanduser("~")))
    with open(config_file_path, 'r') as stream:
        try:
            print(yaml.safe_load(stream))
        except yaml.YAMLError as exc:
            print(exc)


if __name__ == '__main__':
    load_config(None)